- src/ngx_pagespeed.cc
We should not rename the ETag header to work around the gzip module
clearing it, when the gzip module actually isn't built. In that case
we will fail to inject the header filter that renames the header back
to 'ETag' before it gets send out.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/770
> gzip-vs-etag: Don't rename the ETag when gzip isn't ./configured

- config
- src/ngx_base_fetch.cc
- src/ngx_base_fetch.h
- src/ngx_event_connection.cc
- src/ngx_event_connection.h
- src/ngx_fetch.cc
- src/ngx_fetch.h
- src/ngx_pagespeed.cc
- src/ngx_pagespeed.h
- src/ngx_rewrite_driver_factory.cc
- src/ngx_url_async_fetcher.cc
- src/ngx_url_async_fetcher.h
Re-applies the single fd patch, plus a commit  which fixes the `NgxBaseFetch` leak that occurred in the system tests at the point it reloaded configuration.
> Oschaaf single fd fixed

- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
- Fixes an issue in the html flow that would prevent overriding the
value of the 'Server' response-header.
- Add tests that ensure we emit a single and correct server header
in all flows when not overriding it.
- Add tests that ensure overriding the 'Server' response header
works. The resource and IPRO flow are added to the expected failures
as those are not working yet (and will be adressed in a follow-up).
Fixed https://github.com/pagespeed/ngx_pagespeed/issues/864 (html flow)
> server-header: improve handling of server header

- src/ngx_base_fetch.cc
- src/ngx_base_fetch.h
- src/ngx_pagespeed.cc
- Don't construct `NgxBaseFetch` instances and call `Done(false)` later when it turns out it wasn't needed.
- Track the purpose of the base fetch instead of just wether it is an IPRO lookup or not for more informational tracing
as well as avoiding constructing base fetches when their purpose isn't know yet.
- Don't initiate a property cache lookup when we won't need it (`ProxyFetchFactory::InitiatePropertyCacheLookup`)
- Improve IPRO handling of `NgxBaseFetch` and make it clearer. Indicate we want to supress further events when the
base fetch was used to lookup an IPRO url, and the result was not indicative of something we can respond with to the
browser.
- Remove unused `RequestRouting` constants
> base-fetch: prevent unused constructions and prop. cache lookups

- src/ngx_base_fetch.cc
- src/ngx_pagespeed.cc
- src/ngx_pagespeed.h
Get rid of write_pending & fetch_done flags on the request context.
Assume that having ctx->base_fetch set means we have outstanding
work and thus we are not done yet, for simplicity.
This also means we'll release the base fetch earlier which seems
like a good idea to me.
> Release base fetch early, eliminate write_pending and fetch_done

- src/ngx_base_fetch.h
- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
This change passes on non succesful status codes for pagespeed
resources and other places where we act as a content handler to
nginx. This has two benefits:
- Instead of a blank page, the user agent receives a formatted
and (hopefully customized and informative) response.
- Header modules are able to operate on that response, which was
requested in https://github.com/pagespeed/ngx_pagespeed/issues/612#issuecomment-58855816
> content-handling-errors: fall back to nginx's default handling

- src/ngx_base_fetch.cc
- src/ngx_base_fetch.h
- src/ngx_event_connection.cc
- src/ngx_event_connection.h
- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
- test/nginx_system_test.sh
- Add a test to make sure all logged output looks sane, whitelisting current errors/warnings.
- Stop our nginx test instances after we are done testing.
- Add tests for shutting down and reloading configuration under high load (depends on ab).
- Reduce the number of keepalive requests in the keepalive tests to speed up test runs.
- Fix exiting with open file descriptors, fix cleanup in nginx's cache manager/loader processes
- Attempt to finish up queued up NgxBaseFetches/requests on shutdown/reload with a timeout
- Under valgrind the blocking rewrite started failing after adding a test for reloading configuration under high load. 
This is an incremental improvement, the shutdown still needs further improvement.
> trunk-tracking-shutdown: improve shutdown code

- config
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
This change adds a flag to optionally position the module at HTTP_AUX_FILTER_MODULES
instead of just in front of the gzip module. Doing so allows header module(s) to
fully manipulate any response headers before they are send to the user-agent.
With https://github.com/pagespeed/ngx_pagespeed/pull/880, SSI no longer hangs,
and other modules using subrequests should not do so either. SSI subrequests are
not optimized when ngx_pagespeed runs at HTTP_AUX_FILTER_MODULES, so the test for
it is added to the expected failures when the tests are run for this module position.
To build with the module respositioned:
POSITION_AUX=true ./configure ......
The same variable can be set before running the system tests, in which case it will
perform additional header tests and add the SSI test to the …
> module-position: optional switch to install at HTTP_AUX_FILTER_MODULES

- src/ngx_pagespeed.cc
With this change tests should finish with sane logging for the current test workload, 
which means all pending requests and `NgxBaseFetch` instances are handled.
We might also want to add more tests for the shutdown and reload where:
- very slow to respond pages are proxied.
- very long running chunky html pages are proxies
- with pages that reference very slow resources to stress the shutdown of the fetchers
This change also has some minor cleanup
> shutdown: fix system test failure in error.log sanity check

- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Nginx sometimes receives an expected response from 8.8.8.8 when
resolving host names, and the subsequent retry doesn't finish up
in 10 seconds. Bumping the timeout helps, but does not fully
explain why nginx is sometimes receiving an unexpected response.
I'll create a separate issue for investigating that.
> native-fetcher: bump dns timeout to deflake running the tests

- src/ngx_fetch.cc
AsyncFetch::Done will delete itself. Accessing
async_fetch_->extra_respond_headers() will crash nginx.
Updated @basek his patch from https://github.com/pagespeed/ngx_pagespeed/pull/755 
to apply to the current codebase.
> Call async_fetch_->Done after all usages.

- src/ngx_fetch.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
While starting to look into https://github.com/pagespeed/ngx_pagespeed/issues/918,
I noticed a few things that looked off. So:
- Add handling for header only responses
- Fixup i/o event handling
- Fixup NgxFetch's state transitions while handling i/o
Should help stabilizing (valgrind) test runs some more.
Native-fetcher specific tests will be added as a follow-up to this, after sorting out #918 .
> native-fetcher: fix a few bugs

- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
- src/ngx_url_async_fetcher.cc
- Native fetching broke in https://github.com/pagespeed/ngx_pagespeed/pull/925
Make changes so we can do early-stage fetches in the startup process
to fix that.
- Properly cancel out any pending fetches upon ShutDown()
- Decline fetching after ShutDown(), decline fetching when Init()
failed.
> native-fetcher: fixes

- test/nginx_system_test.sh
remove unneeded "unexpected response" inverse grep from system test that was readded in #925
> rm "unexpected response" grep from system test

- src/ngx_base_fetch.cc
removes an unused variable when compile without NGX_DEBUG, allows for
building with -Werror.
> move 'type' variable to inside an #if statement

- src/ngx_pagespeed.cc
The last argument was not actually used, and hence was removed.
> Adjust to API change to InitiatePropertyCacheLookup

- src/ngx_pagespeed.cc
- src/ngx_server_context.cc
initialize some uninitialized variables to allow building with clang with fewer warnings/errors.
after this and a change to PSOL, building with clang works with the following CFLAGS.
`CC=clang CXX=clang++ CFLAGS="-Wno-c++11-extensions" ` 
closes #950
> initialize uninitialized variables.

- src/ngx_rewrite_options.cc
When configuring downstream caching if you have an origin with multiple caches in front of it you might want to choose how you handle requests in response to which cache you're getting them from.  White-list `DownstreamCachePurgeLocationPrefix`, `DownstreamCachePurgeMethod`, and `DownstreamCacheRewrittenPercentageThreshold` for scripting so this is possible.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/903
> config: whitelist a few more directives for script variables

- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Backport of:
- Fixes an issue in the html flow that would prevent overriding the
value of the 'Server' response-header.
- Add tests that ensure we emit a single and correct server header
in all flows when not overriding it.
- Add tests that ensure overriding the 'Server' response header
works. The resource and IPRO flow are added to the expected failures
as those are not working yet (and will be adressed in a follow-up).
Fixed https://github.com/pagespeed/ngx_pagespeed/issues/864 (html flow)
> backport #864 fix for bugfix release

- test/nginx_system_test.sh
Slow file operations can result now in error logs, and those can occur when running valgrind tests.  We need to ignore those in a grep for errors in the error log.
> ignore errors about slow file operations

- config
Pull @PiotrSikora 's fix from #1045 onto trunk-tracking.
This did mean fixing up some merge conflicts: trunk-tracking (which is newer than master) has a `position_aux` option.
> Fix interaction with ngx_brotli module.

- src/ngx_rewrite_options.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
We want this so people can turn off ShardDomain with http2/spdy.
This change also depends on a small change in PSOL:
```
rewriter/rewrite_options.cc:
RewriteOptions::ParseAndSetOptionFromName2(
} else if (StringCaseEqual(name, kMapRewriteDomain)) {
WriteableDomainLawyer()->AddRewriteDomainMapping(arg1, arg2, handler);
} else if (StringCaseEqual(name, kShardDomain)) {
-    WriteableDomainLawyer()->AddShard(arg1, arg2, handler);
+    if (arg2.empty()) {
+      // We allow people to put:
+      //   pagespeed ShardDomain domain_to_shard "";
+      // because we want people to be able to use script variables in nginx to
+      // disable domain sharding with spdy/http2.
+      // See pagespeed/module/https_support#h2_configuration_nginx
+    } else {
+ …
```
> Support script variables in ShardDomain

- config
(built with 4.8)
See issue 942
> Pass in -D_GLIBCXX_USE_CXX11_ABI=0, so people using gcc-5.x can use our psol.a

- src/ngx_pagespeed.cc
- src/ngx_pagespeed.h
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Only set headers_out->location when the upstream originally did
as well. If the Location: header value involved starts with "/"
nginx will absolutify it, ignoring any X-Forwarded-Proto header
in the process.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/819
(Confirmed: https://github.com/pagespeed/ngx_pagespeed/issues/1029)
Hopefully fixes https://github.com/pagespeed/ngx_pagespeed/issues/711
> location-header: Be careful with headers_out->location

- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Checking this in proactively will help me make a mod_pagespeed test change without breaking the nginx tests.
> suppress errors on new 2-pass and 3-pass ipro tests

- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
It turns out to be possible to initialize logging earlier by
grabbing the log from a global ngx_cycle structure.
This makes us start logging earlier, yet loses the
"No threading detected ..." messages both from stderr and
in error.log when nginx initially starts.
With this change, these messages will now be logged as we start
logging earlier:
"
flush
.
"
These originate from SystemCachePath::CacheKey which appends
newlines to the key, and the resulting cache key ends up being
logged. We might want to change that (on the mps side), because the resulting
lines in error.log look weird and might raise questions.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/895
> log: initialize logging earlier

- src/ngx_pagespeed.cc
- Fix potentially sending the location header into PSOL twice.
- Be more thorough when unsetting the location header
Attempts to fix #725
from oschaaf
> reapply:  location-header: tweak location header handling

- src/ngx_base_fetch.cc
- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
- Fix nginx-side flow so we handle .pagespeed. resources ok
when they will land on a customized 404 internal location.
- Additionally, check for a wiped request context and make sure
we do not dereference a null pointer, which is what hurt in
the flow we entered above as the IPRO lookup still was
generating events while the nginx side request context was
gone.
- Also, as a preliminary measure, do not check fail when we
receive a stale event originating from a NgxBaseFetch that
is no longer associated with our request context.
Do log a warning so we'll hear about this happening either
through system test failures or a bug report.
Fixes #1081
> Fix crasher on 404 .pagespeed. resources w/a custom location

- src/ngx_base_fetch.cc
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1096
> Eliminate CHECK that fails (rarely) during the IPRO lookup.

- src/ngx_base_fetch.cc
We should not use r->connection after we finalize the request.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1100
> Fix valgrind complaint caused by NgxBaseFetch

- src/ngx_fetch.cc
Counterpart of:
https://github.com/pagespeed/mod_pagespeed/commit/f3639e84c0196a5f5151ff5e54ad57285db09b37
> Adjust our UA string to fix to make it compatible with fonts.g.c parsing on IE11.

- src/ngx_pagespeed.cc
> Fix a typo

- config
As of 1.9.11, nginx supports loading dynamic modules
This change makes us support building ngx_pagespeed.so
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1116
>  Support building ngx_pagespeed as a dynamic module

- test/pagespeed_test.conf.template
For backward compatibility, only allow varying on Accept header for ipro-for-browser.example.com
> Allow varying on Accept header for ipro-for-browser.example.com

- test/pagespeed_test.conf.template
Add 2 servers for testing image rewrites in IPRO. Together with the existing server, ipro-for-browser.example.com, we will be testing testing image rewrites under different settings, in particular, include "AllowVaryOn" of "Auto", "Accept", and "None".
> Add system tests for image format, quality, and response in IPRO

- src/ngx_pagespeed.cc
- src/ngx_pagespeed.h
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
The report from some time ago mentioned three Vary: headers,
but I can now only reproduce two using trunk-tracking plus the
original repro-configuration.
This fix unflags r->gzip_vary as set by the gzip module when PSOL
hands us Vary: Accept-Encoding, to make sure that nginx's core
header filter doesn't append another one.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1064
> vary-header: Emit a single vary header in the IPRO flow

- src/ngx_fetch.cc
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1148
> NgxFetch: Log url and error when url parsing fails.

- test/nginx_system_test.sh
Apparently, when running in emacs and piped into another command, ps limits
it's output to COLUMNS making check_process_names fail.  Telling ps to use
wide, wide output with 'ww' fixes this.
Additionally, use check_from so that if this test does fail we can debug
it better, seeing what grep was looking at.
> controller: don't fail tests when running in emacs

- config
- config.make
Explain why we do it via config.make better.
Remove partial workaround for config.make not invoked for dynamic modules,
nginx dev fixes the root issue, and the workaround is insufficient anyway.
> Turn on C++11 for all compilers, not just clang.

- src/ngx_pagespeed.cc
This change makes nginx close the request when we receive a close
event or RST_STREAM while waiting for an async PSOL op to complete
by setting a read event handler, as inspired by the limit request
module from nginx.
Should fix https://github.com/pagespeed/ngx_pagespeed/issues/1146
> Fix for async waits vs client aborts and HTTP/2 RST_FRAMES

- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Instead, use a new (not-yet-committed) target in Makefile.tests to build
a mirror htdocs in test/tmp/root that sym-links the large readonly
section and deep copies the test areas for purge and flush tests.
This must be committed alongside https://github.com/pagespeed/mod_pagespeed/pull/1306
> During system-tests, don't write into the source-controlled htdocs area.

- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
Needed for ImageMaxRewritesAtOnce to work with latest revisions.
> Sync top-level process scope options into RewriteDriverFactory::default_options

- src/ngx_rewrite_options.cc
The renaming is to make it clear that kProcessScopeStrict (aka what
ngx_pagespeed does for everything already) is what new code should be
using, rather than current kProcessScope/upcoming kLegacyProcessScope
which does weird backwards compatible things in mod_pagespeed.
> Update for API: kProcessScope is about to become kLegacyProcessScope

- .travis.yml
for some reason we were still using the svn for travis here, but git for everything else...
> svn of depot_tools is going away, migrate to git.

- src/ngx_rewrite_driver_factory.cc
When there is no top-level configuration but only server configuration,
we don't have main options to set and consider. This prevents
a NULL dereference in that case. (Later on we'll write out a message
about why we cannot startup with this configuration).
> Fix for when there is only server-level configuration

- src/ngx_pagespeed.cc
While diagnosing a problem on the mps discussion [1] list I noticed that when using the following configuration ngx_pagespeed would still pass html through PageSpeed:
```
pagespeed Disallow *;
```
This PR changes that, which seems on par with mod_pagespeed when I look at the code.
[1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mod-pagespeed-discuss/ReOcIWbH7DE/RgQSIhUyBgAJ
> Check options->IsAllowed() before rewriting html.

- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
- test/pagespeed_test.conf.template
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1190
> rewrite-options: don't turn on CoreFilters just because of query params

- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- src/ngx_rewrite_driver_factory.h
- src/ngx_rewrite_options.cc
- src/ngx_rewrite_options.h
- test/pagespeed_test.conf.template
All directory- and process- scoped options are allowed with this
change, when "ProcessScriptVariables all" is specified.
Option list compiled from:
https://docs.google.com/spreadsheets/d/1qJSUZqd2Te-4SDtm1Av6u-AckNv_oHEp1qdaUjNqZoM/edit#gid=0
> Allow processing of script variablies in more options

- src/ngx_message_handler.cc
Nginx side of a change which adds `SystemMessageBuffer::AddMessageToBuffer(type, file, line, message)` and fixes similar bug in `ApacheMessageHandler`.
> Make NgxMessageHandler::FileMessage() add data into internal buffer as well

- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
allow 'adding function to sequence' warnings on shutdown, without breaking the nginx debug tests
> allow sloppy exit

- config
This is needed because the current GURL implementation there --- and hence
google_url.h needs an extra compat header that's there.
> Also look for headers in /url in mod_pagespeed tree

- test/valgrind.sup
This passes checkin tests, but I'm wondering if it might be better to just add a blanket suppression for everything under RE2::Compile
> Additional suppressions for new RE2

- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
After calling ngx_http_filter_finalize_request return NGX_DONE
as we are still in pre-access phase. This bug shows up when the
"special" response is generated from, for example, php as opposed
to a static file.
Second part of the fix for
https://github.com/pagespeed/ngx_pagespeed/issues/1146
> special-responses: fix for hanging sometimes on special responses

- config
Put it on trunk-tracking too.
(Already added to branch 33 in https://github.com/pagespeed/ngx_pagespeed/pull/1273)
> We need -lstdc++ to come after psol.a (#1273)

- scripts/build_ngx_pagespeed.sh
If you enter --with-cc-opt='-arg1 -arg2' when the script asks for
additional arguments we want that to remain as one chunk all the way
through to being a single argument to ./configure
> build_ngx_pagespeed: handle quoted arguments

- test/nginx_system_test.sh
I have a parallel change in PSOL that refactors out the duplication here and moves the `curl` setup into `check_flushes`.
> tests: check flushing changed its arguments

- scripts/build_ngx_pagespeed.sh
We want to parse `$additional_configure_arg`s into an array the way the
shell would, which we're using `eval` for.  But because we were missing
quotes whitespace was being stripped.  Basically:
$ function lines() { for x in "$@"; do echo "$x"; done; }
$ lines a "b   c" d
a
b   c
d
$ a='a "b   c" d'
$ eval e=($a)
$ eval f=("$a")
$ lines "${e[@]}"
a
b c
d
$ lines "${f[@]}"
a
b   c
d
We were doing this like `e` when we should have been doing it like `f`.
> install: fix quoting

- test/nginx_system_test.sh
Followup to cd004c6d0c1389602f7493d840b3226ca47313a4
> testing: check_flushing needs to know the host name

- scripts/build_ngx_pagespeed.sh
The script succeeded but the exit code is 1 because it's not a dryrun so the last command failed.
> Fix non-zero exit code even if the script succeed

- .travis.yml
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
- test/run_tests.sh
Right now run_tests.sh assumes it has 8053 and 9991 without causing any
problems.  Start assuming we have 8050 and 8051 as well instead of
requiring people to pass them in.
> test: run_tests.sh should just assume 8050 and 8051

- test/pagespeed_test.conf.template
Add a new server-name to help test a repro for broken pagespeed resorces
after ipro-recorded optimations.
for https://github.com/pagespeed/mod_pagespeed/issues/1145
and https://github.com/pagespeed/ngx_pagespeed/issues/1319 .
> Add a new server-name to help test a repro for issue 1319

- scripts/build_ngx_pagespeed.sh
A user-friendly check with dynamic module building tries to warn people early if the version of ngx_pagespeed they're building is too old to be compiled as a dynamic module, but this can't work with tags.  If we're given something other than a numeric version number, don't try to perform this check.
Fixes https://github.com/pagespeed/mod_pagespeed/issues/1443
> installer: allow --dynamic-module to be used with tags

- scripts/build_ngx_pagespeed.sh
- scripts/format_binary_url.sh
- scripts/pagespeed_libraries_generator.sh
A few bash files were missing license comments
> licensing: correct bash license comments

- config
> config: use Release binaries when building with --with-debug if that's all that's available

- .travis.yml
- config
I initially planned to get this working on Ubuntu 12, but decided it wasn't
worth it and switched to Ubuntu 14 (Trusty).  Now it passes tests on Travis, so
I've added other people's emails back to the set of people to send emails to.
Also update mps while we're at it.
> travis: get it building and passing tests

- src/ngx_pagespeed.cc
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1361 by expanding the "is pagespeed disabled" checks to check both "were there no pagespeed configuration directives" and "were we unplugged" instead of just the former.
> Allow use of "unplugged" without crashing

- test/nginx_system_test.sh
Eventually we'll convert remote_config_system_test.sh and nginx_system_test.sh
to use run_test, but until then when TEST_TO_RUN is specified we should skip
the tests in those files and just run system/system_test.sh
> fix TEST_TO_RUN in ngx_pagespeed

- scripts/build_ngx_pagespeed.sh
- scripts/rebuild.sh
- test/run_tests.sh
* provide scripts/rebuild.sh so you don't have to run make commands in
two directories
* make test/run_tests.sh able to run with no arguments by setting good defaults.
> devel: simplify ngx_pagespeed development flow

- src/ngx_pagespeed.cc
- src/ngx_rewrite_options.cc
- test/pagespeed_test.conf.template
Add standby mode for ngx_pagespeed, equivalent to "off" in mod_pagespeed.
With this change "off" is deprecated, and people should use "unplugged" instead.
See also: https://github.com/pagespeed/mod_pagespeed/pull/1482
Fixes: https://github.com/pagespeed/ngx_pagespeed/issues/968
> standby: add standby mode

- src/ngx_pagespeed.cc
Mind r->header_only when processing the response body.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1375
> Don't respond with an entitybody to HEAD requests for html

- src/ngx_pagespeed.cc
* Compilation of ngx_pagespeed broke with the following commit in
nginx: https://github.com/nginx/nginx/commit/129b06dc5dfab7b4513a4f274b3778cd9b8a6a22
This change intends to unbreak it while maintaining backwards
compatibility.
* updates the nginx testing-dependency to 1.13.4
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1451
> nginx 1.13.4: Fix compilation error

- src/ngx_pagespeed.cc
PR #1453 was merged too soon, using this PR to address
https://github.com/pagespeed/ngx_pagespeed/pull/1453#discussion_r134222719
(Sorry Josh!)
> Adress @jmarantz his comment from #1453's review

- scripts/build_ngx_pagespeed.sh
> Update build script to pass --skip_deps when called with --no-deps-check

- scripts/build_ngx_pagespeed.sh
This time the script is actually run as manual testing
> Fix syntax of script

- src/ngx_pagespeed.cc
I got issue compiling with nginx 1.13.3 with master
since the enum `NGX_HTTP_PRECONTENT_PHASE` is only added after `1.13.4`
Error message was:
```
/usr/local/src/ngx_pagespeed/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_init(ngx_conf_t*)’:
/usr/local/src/ngx_pagespeed/src/ngx_pagespeed.cc:3089:17: error: ‘NGX_HTTP_PRECONTENT_PHASE’ was not declared in this scope
int phase = NGX_HTTP_PRECONTENT_PHASE;
^
```
Related change was introduced in https://github.com/pagespeed/ngx_pagespeed/pull/1453
> Fix compiling issue with older nginx

- src/ngx_pagespeed.cc
Address a mistake I made in https://github.com/pagespeed/ngx_pagespeed/pull/1458
While testing the draft for 1.12.34.3 I noticed that older nginx
versions would fail to compile. Switch kNginx13_1_4 to a #define so we
can use it to properly compare.
> nginx-1.13.4: use preprocessor define instead of const for comparison

- src/ngx_event_connection.cc
Bump the pipe capacity, because running out of buffer space may cause
a write to spin indefinitely on EAGAIN.
Bumping the pipe capacity should eliminate the problem in practice,
though in theory the module could still be subject to it.
For now, leaving behind a todo with a suggested solution (should
the problem ever show up again).
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1380
> Fix nginx worker 100% cpu usage (spinning on write returning EAGAIN)

- config
Hi,
I gave the PSOL_BINARY environment variable to skip queries due to # 1332 change on build with `--with-debug`. Then, since `buildtype=Debug` is set, there is no file to include.
I want to use `buildtype=$PSOL_BUILDTYPE` if there is a PSOL_BUILDTYPE environment to avoid that case.
> set buildtype from env PSOL_BUILDTYPE.

- scripts/build_ngx_pagespeed.sh
- Fix auto-install of required packages by fixing quoting (thanks @jeffkaufman!). 
- Add libuuid-devel for redhat-based distro's too.
Fixes https://github.com/pagespeed/mod_pagespeed/issues/1680
> Fix ngx_pagespeed installing dependency packages

- src/ngx_event_connection.cc
Kernels before 2.6.35 do not have F_SETPIPE_SZ defined.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1503
> F_SETPIPE_SZ: check for existence before using

- .gitmodules
- PSOL_BINARY_URL
- config
- scripts/build_ngx_pagespeed.sh
- scripts/pagespeed_libraries_generator.sh
- src/ngx_base_fetch.cc
- src/ngx_event_connection.cc
- src/ngx_fetch.cc
- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
- test/pagespeed_test.conf.template
- test/valgrind.sup
Update sources to reflect that the source of truth for most of the
repositories in pagespeed/ have moved to
github.com/apache/incubator-pagespeed-*
> Update repository links

- scripts/build_ngx_pagespeed.sh
Currently running `build_ngx_pagespeed.sh` with `--assume-yes` won't automatically send yes when installing dependencies, defeating the purpose. Minor patch which adds `-y` to install commands if `--assume-yes` is used. I may have missed a spot, but I think I got all install commands.
> Honor assume yes when installing dependencies

- scripts/build_ngx_pagespeed.sh
`wget` is a required dependency for the build script but wasn't in the dependency list for Debian-based distros, although it was listed in the Redhat-based distro dependencies. PR simply adds it to the dependency list.
This PR along with the merged #1552 allow the build script to work out-of-the-box on the `ubuntu` Docker image when using `--assume-yes`.
> Add wget as dependency for Debian-based distros in build script

- docker/alpine-3.8/nginx-mainline/Dockerfile
- docker/alpine-3.8/nginx-stable/Dockerfile
- docker/alpine-edge/nginx-mainline/Dockerfile
- docker/alpine-edge/nginx-stable/Dockerfile
Stable from 1.14.0 to 1.14.1
Mainline from 1.15.5 to 1.15.6
http://nginx.org/en/security_advisories.html
> Update Nginx in Docker

- scripts/format_binary_url.sh
Because of the word boundary \b sed fails to replace $BIT_SIZE_NAME from the binary url in macOS.
Related issue: #1606
> removing the word boundary \b

- src/ngx_pagespeed.cc
Return NULL instead of NGX_CONF_ERROR when config creation fails.
Fixes https://github.com/apache/incubator-pagespeed-ngx/issues/1623
> Fix error handling in ps_create_XXX_conf

- scripts/format_binary_url.sh
This script runs fine with just Dash (SH) instead of Bash. Alpine Linux and others don't have Bash.
> Avoids relying on Bash
