apache/incubator-pagespeed-ngx

- src/ngx_base_fetch.cc
Request termination code relies on posted requests being run.
One of the things this fixes is that we won't hang when configured
to run before the SSI module.
Avoids trouble when changing the module order, which helps
https://github.com/pagespeed/ngx_pagespeed/issues/612
> posted-requests: run posted requests when appropriate

- src/ngx_pagespeed.cc
Fixes #888 along with
https://code.google.com/p/modpagespeed/source/detail?r=4533
I'll also cherry-pick this into master.
> Replace CHECK with return failure and log.

- test/nginx_system_test.sh
After sending a SIGHUP, wait for the new worker process with the
new configuration to handle further requests, or else the tests
running after that might get confused when the new worker becomes
active with fresh shared mem statistics and shared mem cache.
> configuration-reload-test: wait for the new worker to get ready

- src/ngx_pagespeed.cc
Should fix https://github.com/pagespeed/ngx_pagespeed/issues/913
> date-header: fix 32 bits issue

- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
- test/run_tests.sh
Deleting other one that I broke squashing.
> Port remote configuration option to nginx.

- src/ngx_message_handler.h
- src/ngx_rewrite_driver_factory.h
addresses issue #948
I'll cherry-pick this to trunk-tracking when this is merged.
> add support for nginx 1.7.11 --with-threads

- test/pagespeed_test.conf.template
waiting on apache change to go in to merge, will then cherry-pick to master for 1.9.32.6 point release.
> add test servers for sending x-sendfile and x-accel-redirect

- src/ngx_pagespeed.cc
RewriteDriver::SetRequestHeaders already pulls the UA from the request-headers.
> Don't call RewriteDriver::SetUserAgent on the UA in the request-headers.

- src/ngx_base_fetch.cc
- src/ngx_base_fetch.h
- src/ngx_pagespeed.cc
- src/ngx_server_context.h
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
- test/run_tests.sh
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1015
Pull with MPS Side for this change:
https://github.com/pagespeed/mod_pagespeed/pull/1161
> IPRO+MPD: Make In-Place-Resource-Optimization with MapProxyDomain work

- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
- test/pagespeed_test.conf.template
Nginx side of the fix for https://github.com/pagespeed/mod_pagespeed/issues/1088
> Add support for blocking access to our handlers.

- src/ngx_pagespeed.cc
this change is required for gzip cache change going into mod_pagespeed.
> add content_encoding to headers_out

- config
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1021
> Fix interaction with ngx_brotli module.

- config
- config.make
- src/log_message_handler.cc
and make us actually build with clang (the log_message_handler.cc change
and config.make change)
> Add compiler version checks for what we want to support going forward,

- config
> add flags for new GCC on config tests

- test/pagespeed_test.conf.template
nps side of https://github.com/pagespeed/mod_pagespeed/pull/1200
> AddResourceHeader: Add test configuration

- src/ngx_pagespeed.cc
(Upcoming on mod_pagespeed end)
> Adjust to library API change: no more spdy-specific config.

- config
Note: this commit doesn't add support for dynamic modules, just fixes the build.
Fixes #1110.
> Fix build with nginx-1.9.11+.

- src/ngx_pagespeed.cc
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1120
> Fix shutdown when ngx_pagespeed is completely disabled.

- src/ngx_pagespeed.cc
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1138
> IPRO: Copy the cache control value to ensure a correct lifetime

- src/ngx_pagespeed.cc
- test/pagespeed_test.conf.template
mps change: https://github.com/pagespeed/mod_pagespeed/commit/689e3f1a0dd70c8585a2304c044b4408a8da0bc3
> Companion to mps change to set s-maxage on unoptimized ipro resources

- test/run_tests.sh
run_tests had the wrong invocation of the script in the comments. fix
that.
> fix up the description in the run_tests.sh

- .travis.yml
add travis-ci to the trunk tracking branch. I haven't gotten tests to work yet, but checking that builds are successful is at least useful on new pull requests.
I'll follow up with one that runs the tests next.
> add travis to trunk-tracking branch

- src/ngx_base_fetch.cc
- src/ngx_base_fetch.h
- src/ngx_pagespeed.cc
- test/nginx_system_test.sh
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1192
May also fix https://github.com/pagespeed/ngx_pagespeed/issues/1172
> respect purge requests when serving ipro requests from ngx_pagespeed

- test/nginx_system_test.sh
... rather than having the Makefile depend on PWD.
> Pass the install-path into Makefile

- src/ngx_pagespeed.cc
Should fix https://github.com/pagespeed/ngx_pagespeed/issues/1220
> Fix segfault when there's no http{} block in nginx.conf

- test/pagespeed_test.conf.template
Needed for fixing https://github.com/pagespeed/mod_pagespeed/issues/1350
> rewrite-domains: add test configuration for rewriting static assets

- test/pagespeed_test.conf.template
nginx side of the change
https://github.com/pagespeed/mod_pagespeed/issues/1371
> nginx side of https://github.com/pagespeed/mod_pagespeed/issues/1371

- test/nginx_system_test.sh
so run it from the master test script
> the remote config test is in a separate script now

- PSOL_BINARY_URL
- config
- scripts/build_ngx_pagespeed.sh
Automated version of the instructions on https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source
Tested on fresh vms of debian8, centos 6 and 7, rhel 6 and 7, and ubuntu lts 12, 14, and 16
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1262
> install: add script to install nginx_pagespeed

- test/pagespeed_test.conf.template
nginx side of the fix for https://github.com/pagespeed/mod_pagespeed/issues/1386
> load-from-file: config for testing load from file with a low size limit

- README.md
- scripts/build_ngx_pagespeed.sh
Followup to https://github.com/pagespeed/ngx_pagespeed/pull/1329
> branch-names: now that trunk-tracking is master, update references

- scripts/build_ngx_pagespeed.sh
Instead of requiring people to answer a prompt to specify which additional
arguments they would like nginx to be built with, allow people to specify
arguments like this on the command line.  The quoting is not ideal, since
it's important to pass spaces etc properly all the way through to the
underlying commands, but I give an example in the help text.
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1340
> install: add --additional-nginx-configure-arguments option

- src/ngx_pagespeed.cc
Revert commit 149c47ace4e7251f1b56c8805c7e7cea0ea28147
(The plan is to tag `1.12.34.2` as stable, so no code changes)
> Revert "stop crashing when unplugged"

- test/pagespeed_test.conf.template
(mod_pagespeed commit a7c39a1b5a14f1422fef19e8e9dcb11074ba1c65)
This should make CI pass tests
> Update mod_pagespeed testing dependency

- src/ngx_pagespeed.cc
Fix for https://github.com/pagespeed/ngx_pagespeed/issues/1465
> Fix ignored return code in ps_simple_handler()

- src/ngx_pagespeed.cc
- src/ngx_rewrite_driver_factory.cc
> Proposed changes for releasing 1.12.34.3-stable (ngx_pagespeed only)

- src/ngx_base_fetch.cc
Hi there, 
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
> Fixed Spelling.
